DWAPlannerROS:
  max_vel_x: 0.22
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  acc_lim_x: 0.5
  acc_lim_theta: 1.0

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false

  sim_time: 1.5
  vx_samples: 10
  vtheta_samples: 20
  controller_frequency: 5.0
